/**
 * CLI reference for `hoody chat` retrieval.
 *
 * Regenerated by `bun run refresh-chat-reference`.
 * Determinism-gated by a dedicated unit test.
 */
export interface RefCommand {
    path: string;
    summary: string;
    flags: string[];
}
export interface RefGroup {
    name: string;
    aliases: string[];
    description: string;
    commands: RefCommand[];
}
export interface CliReference {
    groups: RefGroup[];
}
export declare const CLI_REFERENCE: CliReference;
