// AUTOGENERATED — DO NOT EDIT BY HAND.
//
// Vendored from the upstream Hoody curl client, renamed at the boundary:
//   Channel            → CurlChannel
//   ChannelStream      → CurlChannelStream
//   createFetch        → createCurlFetch
//   ChannelFetch       → CurlFetch
//   CreateFetchOptions → CurlFetchOptions
//
// Internal cross-module imports are stripped — every reference resolves
// within this single file.
/* eslint-disable */


// ════════════════════════════════════════════════════════════════════════
// VENDORED: types.ts
// ════════════════════════════════════════════════════════════════════════

// Wire-format types for the the upstream curl kit multiplexed request channel.
// Matches `ChannelServerMessage` / `ChannelClientMessage` in
// the upstream curl protocol.

/** Execution mode passed via CurlRequest.mode. */
export type ExecutionMode = "sync" | "async";

/**
 * CurlRequest mirrors the server's serde shape (snake_case). Field set kept
 * in sync with the upstream curl protocol `CurlRequest`.
 *
 * Note: the following fields exist server-side but are REJECTED at validation
 * (`proxy`, `proxy_user`, `proxy_password`, `cacert`, `cert`, `key`) — they
 * are NOT exposed here because sending any of them returns 400. The TLS
 * client-cert fields (cacert/cert/key) accept filesystem paths; until the
 * server gets a `--cert-dir` flag they remain rejected.
 */
export interface CurlRequest {
  url: string;
  method?: string;
  headers?: Record<string, string>;
  user_agent?: string;
  referer?: string;
  cookie?: string;
  auth_user?: string;
  auth_password?: string;
  auth_method?: "basic" | "digest" | "ntlm" | "negotiate";
  bearer_token?: string;
  data?: string;
  /**
   * Raw binary request body. SDK-internal: it is NEVER serialized into the
   * `request.start` JSON (the server would reject the unknown field). When
   * present on a binary-negotiated channel, the SDK strips it from the JSON
   * envelope and uploads the bytes in a separate binary WebSocket frame.
   * Takes precedence over `data`/`json`/`form`.
   */
  data_binary?: Uint8Array;
  json?: unknown;
  form?: Record<string, string>;
  timeout?: number;
  connect_timeout?: number;
  max_redirects?: number;
  follow_redirects?: boolean;
  max_filesize?: number;
  insecure?: boolean;
  cert_type?: "PEM" | "DER";
  compressed?: boolean;
  tcp_nodelay?: boolean;
  keepalive?: boolean;
  keepalive_time?: number;
  range?: string;
  speed_limit?: number;
  speed_time?: number;
  save?: boolean;
  save_path?: string;
  response?: "transparent" | "json";
  /** Server's ExecutionMode enum. Only meaningful on the REST /curl endpoint; the channel always streams. */
  mode?: ExecutionMode;
  job_name?: string;
  session_id?: string;
  retry_count?: number;
  retry_delay?: number;
  /** Cron expression for /schedule (not used on the channel). */
  schedule?: string;
}

export interface ResponseHeader {
  name: string;
  value: string;
}

export interface ResponseTiming {
  total: number;
  namelookup: number;
  connect: number;
  pretransfer: number;
  starttransfer: number;
  redirect: number;
}

export interface ResponseMetadata {
  effective_url: string;
  redirect_count: number;
  size_download: number;
  size_upload: number;
  speed_download: number;
  speed_upload: number;
  content_type: string | null;
}

// ---- client → server ----

export type ChannelClientMessage =
  | {
      type: "request.start";
      stream_id: number;
      request: CurlRequest;
      /** When true, the request body follows in a separate binary frame. */
      binary_body?: boolean;
    }
  | { type: "request.cancel"; stream_id: number }
  | { type: "ping" };

// ---- server → client ----

export interface ChannelLimits {
  max_concurrent_streams: number;
  max_queue: number;
  max_frame_bytes: number;
  max_request_bytes: number;
  chunk_bytes: number;
  stream_timeout_secs: number;
  idle_timeout_secs: number;
  max_outbound_messages: number;
}

export interface ChannelFeatures {
  buffered: boolean;
  streaming: boolean;
  cache: boolean;
  outbound_pooling: boolean;
  sse: boolean;
  /**
   * True when the server negotiated the binary-frame fast path (the client
   * opened the channel with `binary` enabled and the server supports it).
   * When true, response body chunks arrive as raw binary WebSocket frames
   * instead of base64-in-JSON `response.body` messages. Absent on servers
   * that predate the binary protocol.
   */
  binary_frames?: boolean;
}

export interface HelloMessage {
  type: "hello";
  version: number;
  connection_id: string;
  limits: ChannelLimits;
  features: ChannelFeatures;
}

export interface ResponseStartMessage {
  type: "response.start";
  stream_id: number;
  status_code: number;
  headers: Record<string, string>;
  raw_headers: ResponseHeader[];
  content_type: string | null;
  effective_url: string;
  body_bytes: number;
  /** True when upstream was text/event-stream and SSE promotion fired. */
  is_sse?: boolean;
}

export interface ResponseBodyMessage {
  type: "response.body";
  stream_id: number;
  offset: number;
  encoding: "base64";
  data: string;
}

export interface ResponseSseEventMessage {
  type: "response.sse_event";
  stream_id: number;
  seq: number;
  event: string;
  id?: string;
  data: string;
  retry?: number;
  data_truncated?: boolean;
}

export interface ResponseEndMessage {
  type: "response.end";
  stream_id: number;
  timing: ResponseTiming;
  metadata: ResponseMetadata;
  /** Number of SSE events emitted; only set for is_sse streams. */
  sse_events?: number;
}

export type ChannelErrorType =
  | "validation_error"
  | "cancelled"
  | "timeout"
  | "queue_full"
  | "sse_capacity"
  | "sse_max_duration"
  | "execution_error"
  | "internal_error"
  | "protocol_error";

export interface ErrorMessage {
  type: "error";
  stream_id?: number;
  error_type: ChannelErrorType | string;
  message: string;
}

export interface PongMessage {
  type: "pong";
}

export interface AcceptedMessage {
  type: "accepted";
  stream_id: number;
}

export interface CancelledMessage {
  type: "cancelled";
  stream_id: number;
}

export type ChannelServerMessage =
  | HelloMessage
  | PongMessage
  | AcceptedMessage
  | CancelledMessage
  | ResponseStartMessage
  | ResponseBodyMessage
  | ResponseSseEventMessage
  | ResponseEndMessage
  | ErrorMessage;

// ---- public-facing SDK types ----

/** Parsed SSE event delivered via the typed-events iterator. */
export interface SseEvent {
  event: string;
  id?: string;
  data: string;
  retry?: number;
  /** True if the upstream event exceeded the server's per-event byte cap. */
  truncated?: boolean;
  /** Monotonic per-stream sequence number. */
  seq: number;
}

/** CurlChannel error surfaced as a JS Error. */
export class ChannelError extends Error {
  override readonly name = "ChannelError";
  constructor(
    message: string,
    public readonly errorType: string,
    public readonly streamId?: number,
  ) {
    super(message);
  }
}

/**
 * Thrown when an operation is aborted via AbortSignal or request.cancel.
 *
 * When the runtime exposes `DOMException` (modern browsers + Node 17+),
 * `createAbortError()` returns a real `DOMException` with `name="AbortError"`
 * (the WHATWG-spec shape — `instanceof DOMException` checks pass, `name` check
 * passes). On older runtimes (no global `DOMException`), it falls back to this
 * `Error` subclass with `name="AbortError"` and a `cause` field.
 *
 * Both shapes satisfy the most common `err.name === "AbortError"` test, which
 * is what the fetch spec actually requires consumers to use.
 */
export class AbortError extends Error {
  override readonly name = "AbortError";
  constructor(message = "The operation was aborted", options?: { cause?: unknown }) {
    super(message);
    if (options && options.cause !== undefined) {
      (this as { cause?: unknown }).cause = options.cause;
    }
  }
}

/**
 * Construct an abort-flavored error. Returns a real `DOMException` when the
 * runtime supports it, otherwise the `AbortError` class above. Either way,
 * `err.name === "AbortError"` is true and `err instanceof Error` is true.
 */
export function createAbortError(
  message = "The operation was aborted",
  cause?: unknown,
): Error {
  const D = (globalThis as { DOMException?: typeof DOMException }).DOMException;
  if (typeof D === "function") {
    try {
      const e = new D(message, "AbortError");
      if (cause !== undefined) (e as { cause?: unknown }).cause = cause;
      return e as Error;
    } catch {
      // Some older runtimes throw on `new DOMException(...)`. Fall through.
    }
  }
  return new AbortError(message, cause !== undefined ? { cause } : undefined);
}


// ════════════════════════════════════════════════════════════════════════
// VENDORED: ws-transport.ts
// ════════════════════════════════════════════════════════════════════════

// Runtime-agnostic WebSocket transport. Uses the global `WebSocket` in
// browsers / Deno / Bun / Node ≥21, and dynamically imports the `ws` package
// in older Node (≥18 < 21) where the global is missing.

/** A value the transport can put on the wire. Strings are JSON control/data
 * frames; binary values are pre-encoded channel binary frames. */
export type WsSendData = string | ArrayBufferLike | ArrayBufferView;

export interface WsLike {
  readonly readyState: number;
  /** Set to `"arraybuffer"` so inbound binary frames arrive as ArrayBuffers
   * (uniform across the global WebSocket and the `ws` package). */
  binaryType?: string;
  send(data: WsSendData): void;
  close(code?: number, reason?: string): void;
  addEventListener(type: "open", listener: () => void): void;
  addEventListener(type: "message", listener: (ev: { data: unknown }) => void): void;
  addEventListener(type: "close", listener: (ev: { code: number; reason: string }) => void): void;
  addEventListener(type: "error", listener: (ev: unknown) => void): void;
}

export const WS_OPEN = 1;

/** Force binary frames to surface as ArrayBuffer on whichever WS impl we got. */
function preferArrayBuffer(ws: WsLike): void {
  try {
    ws.binaryType = "arraybuffer";
  } catch {
    /* some impls reject the assignment pre-open; the channel decoder also
       accepts Uint8Array / Blob, so this is best-effort. */
  }
}

export async function openWebSocket(url: string): Promise<WsLike> {
  const globalAny = globalThis as unknown as { WebSocket?: new (url: string) => WsLike };
  const Ctor = globalAny.WebSocket;
  if (typeof Ctor === "function") {
    const ws = new Ctor(url);
    preferArrayBuffer(ws);
    return ws;
  }
  // Node fallback: dynamic import. Importer must have `ws` installed.
  // We can't statically import `ws` because it would force a dep in the
  // browser path. The `peerDependencies` declaration in package.json marks it
  // optional.
  let mod: { default: new (url: string) => WsLike };
  try {
    mod = (await import(/* @vite-ignore */ "ws")) as {
      default: new (url: string) => WsLike;
    };
  } catch (e) {
    throw new Error(
      "hoody-sdk: no global WebSocket and the optional `ws` " +
        "package is not installed. Either upgrade to Node ≥21 (which has " +
        "a global WebSocket) or `npm install ws`. Original error: " +
        (e instanceof Error ? e.message : String(e)),
    );
  }
  const ws = new mod.default(url);
  preferArrayBuffer(ws);
  return ws;
}


// ════════════════════════════════════════════════════════════════════════
// VENDORED: channel.ts
// ════════════════════════════════════════════════════════════════════════

// Multiplexed channel client for /api/v1/curl/channel.
//
// One `CurlChannel` owns a single WebSocket and demultiplexes many concurrent
// in-flight `CurlRequest`s by `stream_id`. Each request returns a typed
// `CurlChannelStream` that exposes the response start, the body (as either
// buffered chunks for non-SSE responses or a typed SseEvent iterator for SSE
// upstreams), and the final metadata. Cancellation via AbortSignal flips
// `request.cancel` on the wire.

/** Maximum buffered SSE events per stream before the SDK cancels the upstream and emits a `dropped` synthetic event. Protects against memory-DoS from hostile/fast upstreams. */
export const SSE_EVENT_QUEUE_CAP = 4096;
/** Maximum inbound WS frame size the SDK will JSON.parse. Frames larger than this drop the connection. */
export const MAX_INBOUND_FRAME_BYTES = 16 * 1024 * 1024;

// ---- binary frame format (negotiated via the `binary` channel option) -----
//
// Mirrors the Rust relay's framing in the upstream curl protocol. A binary
// WebSocket frame is a fixed 16-byte little-endian header + raw payload:
//   [0]      u8   version  (BIN_FRAME_VERSION)
//   [1]      u8   kind     (BIN_KIND_BODY | BIN_KIND_REQUEST_BODY)
//   [2..4]   u16  flags    (bit0 = LAST: final body chunk for the stream)
//   [4..8]   u32  reserved (zero)
//   [8..16]  u64  stream_id
//   [16..]   payload bytes
const BIN_FRAME_HEADER_LEN = 16;
const BIN_FRAME_VERSION = 1;
/** server → client: a response body chunk. */
const BIN_KIND_BODY = 1;
/** client → server: a request upload body. */
const BIN_KIND_REQUEST_BODY = 2;

/** Reused UTF-8 decoder for the legacy non-string-frame fallback path —
 * allocating a fresh TextDecoder per frame is needless GC churn. */
const SHARED_TEXT_DECODER = new TextDecoder();

/** Encode a client→server binary frame: 16-byte header + payload. */
function encodeBinFrame(
  kind: number,
  flags: number,
  streamId: number,
  payload: Uint8Array,
): Uint8Array {
  const out = new Uint8Array(BIN_FRAME_HEADER_LEN + payload.byteLength);
  const dv = new DataView(out.buffer);
  dv.setUint8(0, BIN_FRAME_VERSION);
  dv.setUint8(1, kind);
  dv.setUint16(2, flags, true);
  dv.setUint32(4, 0, true);
  dv.setBigUint64(8, BigInt(streamId), true);
  out.set(payload, BIN_FRAME_HEADER_LEN);
  return out;
}

/** Configuration for opening a channel. */
export interface ChannelOptions {
  /** WebSocket URL, e.g. `wss://example.com/api/v1/curl/channel`. */
  url: string;
  /** Override the wait for the server's `hello` frame (default 10_000 ms). */
  helloTimeoutMs?: number;
  /** Send a `ping` every N ms to keep idle connections alive (default 25_000). 0 disables. */
  pingIntervalMs?: number;
  /**
   * Suppress the warning that fires when the channel URL is `ws://` and any
   * request includes credential fields (bearer_token, auth_password, cookie,
   * session_id). Set true ONLY if you've independently secured the transport
   * (e.g., loopback / private network).
   */
  silenceInsecureTransportWarning?: boolean;
  /**
   * Auto-reconnect policy. Default ON with exponential backoff. In-flight
   * streams at the moment of disconnect are STILL rejected — reconnect only
   * helps NEW requests issued after the WS reopens. Set `enabled: false` to
   * preserve the v0 behavior (one connection, no reconnect).
   */
  reconnect?: ReconnectOptions;
  /** Observability hooks. All optional; called inline at the relevant lifecycle point. */
  hooks?: ChannelHooks;
  /**
   * Opt into the binary-frame fast path (default `true`). When enabled the
   * SDK opens the channel with `?binary=1`; if the server advertises
   * `features.binary_frames`, response body chunks arrive as raw binary
   * WebSocket frames (no base64 inflation, no JSON parse) and binary request
   * bodies (`CurlRequest.data_binary`) upload as binary frames. Falls back
   * transparently to the text/JSON protocol against servers that don't
   * support it. Set `false` to force the legacy text protocol.
   */
  binary?: boolean;
}

/** Auto-reconnect configuration. */
export interface ReconnectOptions {
  /** Default `true`. */
  enabled?: boolean;
  /** Maximum reconnect attempts (default `Infinity`). */
  maxAttempts?: number;
  /** Initial backoff in ms (default `500`). Each failed attempt doubles up to `maxBackoffMs`. */
  initialBackoffMs?: number;
  /** Cap on backoff (default `30_000` ms). */
  maxBackoffMs?: number;
  /** Jitter range as a fraction of the computed backoff (default `0.2` = ±20%). */
  jitter?: number;
}

/** Lifecycle hooks. */
export interface ChannelHooks {
  /** Fired after the server's `hello` frame is received (initial or reconnect). */
  onOpen?: (hello: ChannelHello) => void;
  /** Fired when the WebSocket closes for any reason. */
  onClose?: (info: { code: number; reason: string; willReconnect: boolean }) => void;
  /** Fired before each reconnect attempt (after the first failure). */
  onReconnecting?: (info: { attempt: number; backoffMs: number }) => void;
  /** Fired when a request is issued via `request()`. */
  onRequestStart?: (info: { streamId: number; url: string; method: string }) => void;
  /** Fired when the server emits `response.start` for any stream. */
  onResponseStart?: (info: { streamId: number; status: number; isSse: boolean }) => void;
  /** Fired when the server emits `response.end` for any stream. */
  onResponseEnd?: (info: { streamId: number; totalBytes: number; sseEvents?: number }) => void;
  /** Fired on connection-level errors (does not duplicate per-stream errors). */
  onError?: (err: Error) => void;
}

/** Server's initial `hello` advertisement (limits + features). */
export type ChannelHello = Omit<HelloMessage, "type">;

/** Per-stream handle returned by `CurlChannel.request()`. */
export class CurlChannelStream {
  /** Resolves once the server emits `response.start`. */
  readonly start: Promise<ResponseStartMessage>;
  /** Resolves once the server emits `response.end` (or rejects on error). */
  readonly end: Promise<ResponseEndMessage>;
  /**
   * ReadableStream of body bytes for non-SSE responses (chunked). Only ONE of
   * `bodyStream` or `body()` may be consumed — they share the same underlying
   * source. Calling `body()` locks/drains the stream.
   */
  readonly bodyStream: ReadableStream<Uint8Array>;
  /** Async iterable of typed SSE events (only meaningful when start.is_sse). */
  readonly events: AsyncIterable<SseEvent>;

  /** Trigger server-side cancellation. */
  readonly cancel: () => void;

  // ---- internal plumbing -----------------------------------------------

  /** @internal */ readonly _streamId: number;
  /** @internal */ _resolveStart!: (m: ResponseStartMessage) => void;
  /** @internal */ _rejectStart!: (e: Error) => void;
  /** @internal */ _resolveEnd!: (m: ResponseEndMessage) => void;
  /** @internal */ _rejectEnd!: (e: Error) => void;
  /** @internal */ _enqueueBodyChunk!: (chunk: Uint8Array) => void;
  /** @internal */ _enqueueSseEvent!: (ev: SseEvent) => void;
  /** @internal */ _closeBody!: () => void;
  /** @internal */ _errorBody!: (e: Error) => void;
  /** @internal */ _closeEvents!: () => void;
  /** @internal */ _errorEvents!: (e: Error) => void;

  constructor(streamId: number, sendCancel: () => void) {
    this._streamId = streamId;
    let startResolve!: (m: ResponseStartMessage) => void;
    let startReject!: (e: Error) => void;
    this.start = new Promise<ResponseStartMessage>((res, rej) => {
      startResolve = res;
      startReject = rej;
    });
    this._resolveStart = startResolve;
    this._rejectStart = startReject;
    this.start.catch(() => {});

    let endResolve!: (m: ResponseEndMessage) => void;
    let endReject!: (e: Error) => void;
    this.end = new Promise<ResponseEndMessage>((res, rej) => {
      endResolve = res;
      endReject = rej;
    });
    this._resolveEnd = endResolve;
    this._rejectEnd = endReject;
    // Auto-attach a no-op rejection handler so that callers who only consume
    // `start` (e.g. the fetch() wrapper) don't trigger an UnhandledPromiseRejection
    // when an AbortSignal or server error rejects `end`/`body`/`events`. Callers
    // who want to observe the rejection still get it via their own .then/await.
    this.end.catch(() => {});

    // ----- body byte stream (used for non-SSE responses) -----
    let bodyController!: ReadableStreamDefaultController<Uint8Array>;
    const bodyStream = new ReadableStream<Uint8Array>(
      {
        start(c) {
          bodyController = c;
        },
        cancel: () => {
          // Caller dropped the stream; signal server-side cancel as well.
          sendCancel();
        },
      },
      // CountQueuingStrategy with highWaterMark caps the internal buffer
      // depth so a slow consumer doesn't accumulate unbounded chunks. When
      // the buffer fills, the stream's `desiredSize` goes negative — the
      // SDK's enqueue path doesn't observe this (no WS-level backpressure
      // to the server), so this is a defense-in-depth limit, not a true
      // backpressure handshake.
      { highWaterMark: 64 },
    );
    this.bodyStream = bodyStream;
    this._enqueueBodyChunk = (chunk) => bodyController.enqueue(chunk);
    this._closeBody = () => {
      try {
        bodyController.close();
      } catch {
        /* already closed */
      }
    };
    this._errorBody = (e) => {
      try {
        bodyController.error(e);
      } catch {
        /* already closed */
      }
    };

    // (body() is a lazy method, see below — defining as a method avoids
    // eagerly locking the stream at construction time.)

    // ----- typed SSE events queue (BOUNDED — see SSE_EVENT_QUEUE_CAP) -----
    // A slow consumer combined with a fast upstream would otherwise grow this
    // array without bound. Cap at SSE_EVENT_QUEUE_CAP entries; when full, the
    // SDK cancels the upstream stream (sends request.cancel) and emits a
    // synthetic `event: dropped` event so the consumer knows data was lost.
    const eventQueue: SseEvent[] = [];
    type EventWaiter = {
      resolve: (v: IteratorResult<SseEvent>) => void;
      reject: (e: Error) => void;
    };
    const eventWaiters: EventWaiter[] = [];
    let eventsClosed = false;
    let eventsError: Error | null = null;
    let queueOverflowed = false;
    this._enqueueSseEvent = (ev) => {
      const waiter = eventWaiters.shift();
      if (waiter) {
        waiter.resolve({ value: ev, done: false });
        return;
      }
      if (eventQueue.length >= SSE_EVENT_QUEUE_CAP) {
        if (!queueOverflowed) {
          queueOverflowed = true;
          // One synthetic event so the consumer learns about the loss.
          eventQueue.push({
            event: "dropped",
            data: JSON.stringify({
              reason: "sdk_event_queue_full",
              cap: SSE_EVENT_QUEUE_CAP,
            }),
            seq: ev.seq,
          });
          // Cancel the upstream stream to stop the flood.
          sendCancel();
        }
        // Silently drop subsequent overflow events.
        return;
      }
      eventQueue.push(ev);
    };
    const onEnd = () => {
      eventsClosed = true;
      while (eventWaiters.length) {
        eventWaiters.shift()!.resolve({ value: undefined as unknown as SseEvent, done: true });
      }
    };
    const onError = (e: Error) => {
      eventsError = e;
      // CRITICAL: pending waiters must RECEIVE the error (reject), not
      // silently complete with done:true. A for-await consumer that's parked
      // on `await iterator.next()` when the error arrives needs the rejection
      // to throw out of the loop — otherwise the loop exits cleanly and the
      // caller never learns the stream failed.
      while (eventWaiters.length) {
        eventWaiters.shift()!.reject(e);
      }
    };
    // Expose these so the channel can wire them inline (avoiding the
    // microtask race that `this.end.then(...)` introduced — between
    // `_resolveEnd` and the .then microtask, a consumer could push a new
    // waiter that would be drained by `onEnd` only on the next tick).
    this._closeEvents = onEnd;
    this._errorEvents = onError;
    const self = this;
    this.events = {
      [Symbol.asyncIterator](): AsyncIterator<SseEvent> {
        return {
          next(): Promise<IteratorResult<SseEvent>> {
            // Drain the buffered queue FIRST. If we surface eventsError early
            // (before reading buffered events), the consumer loses already-
            // received frames — including the synthetic 'dropped' marker.
            const next = eventQueue.shift();
            if (next) return Promise.resolve({ value: next, done: false });
            if (eventsError) return Promise.reject(eventsError);
            if (eventsClosed) return Promise.resolve({ value: undefined as unknown as SseEvent, done: true });
            return new Promise((resolve, reject) => eventWaiters.push({ resolve, reject }));
          },
          return(): Promise<IteratorResult<SseEvent>> {
            self.cancel();
            return Promise.resolve({ value: undefined as unknown as SseEvent, done: true });
          },
        };
      },
    };

    this.cancel = sendCancel;
  }

  /**
   * Drain `bodyStream` into a single `Uint8Array`. Convenience for callers
   * that don't need streaming. Locks the stream — incompatible with
   * `bodyStream` direct consumption.
   */
  async body(): Promise<Uint8Array> {
    // The server's `response.start.body_bytes` is the exact buffered body
    // length, so pre-allocate once and write chunks straight in — no
    // intermediate chunk array and no second concat pass in the common case.
    // Falls back gracefully if the hint is unavailable or a chunk overruns it.
    let expected = 0;
    try {
      const start = await this.start;
      if (Number.isFinite(start.body_bytes) && start.body_bytes > 0) {
        expected = start.body_bytes;
      }
    } catch {
      /* start rejected — the reader below surfaces the same error */
    }
    const reader = this.bodyStream.getReader();
    const out = new Uint8Array(expected);
    let pos = 0;
    const overflow: Uint8Array[] = [];
    // eslint-disable-next-line no-constant-condition
    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      if (pos + value.length <= out.length) {
        out.set(value, pos);
        pos += value.length;
      } else {
        overflow.push(value);
      }
    }
    if (overflow.length === 0) {
      return pos === out.length ? out : out.subarray(0, pos);
    }
    // Hint was short (unexpected for a buffered response): assemble exactly.
    let extra = 0;
    for (const c of overflow) extra += c.length;
    const full = new Uint8Array(pos + extra);
    full.set(out.subarray(0, pos), 0);
    let p = pos;
    for (const c of overflow) {
      full.set(c, p);
      p += c.length;
    }
    return full;
  }
}

/** Per-request invocation options. */
export interface RequestOptions {
  /** AbortController integration — cancel mid-flight. */
  signal?: AbortSignal;
  /**
   * Hard cap on time-to-first-byte (server `response.start`). If exceeded, the
   * SDK fires the cancel and rejects with AbortError. Defaults to no timeout.
   * Recommended for any production code path to prevent hangs on dead WS.
   */
  timeoutMs?: number;
}

/** Main entry point: open a channel, then `.request(curlRequest, {signal})`. */
export class CurlChannel {
  private ws!: WsLike;
  private nextStreamId = 1;
  private streams = new Map<number, CurlChannelStream>();
  // `helloPromise` settles EXACTLY ONCE: resolves on the first-ever successful
  // hello, rejects if the channel permanently closes before ever connecting.
  // `CurlChannel.open()` / `ready()` await this — it is NEVER replaced, so a
  // reconnect during the initial connect can't strand the original awaiter
  // `connectionReady` is the per-connection signal request()'s
  // deferred send waits on; it's renewed each (re)connect cycle so a request
  // issued mid-reconnect waits for the NEW socket rather than racing a dead one.
  private helloPromise: Promise<ChannelHello>;
  private resolveHello!: (h: ChannelHello) => void;
  private rejectHello!: (e: Error) => void;
  private helloSettled = false;
  private connectionReady!: Promise<void>;
  private resolveConnectionReady!: () => void;
  private rejectConnectionReady!: (e: Error) => void;
  private hello: ChannelHello | null = null;
  private closed = false;
  private closeError: Error | null = null;
  private pingTimer: ReturnType<typeof setInterval> | undefined;
  private reconnectTimer: ReturnType<typeof setTimeout> | undefined;
  private reconnectAttempt = 0;
  private readonly options: ChannelOptions;
  private readonly reconnectCfg: Required<ReconnectOptions>;
  private readonly hooks: ChannelHooks;

  private readonly isInsecureTransport: boolean;
  private readonly silenceInsecureWarning: boolean;
  private warnedInsecure = false;
  private warnedUnknownTypes = new Set<string>();

  /** Whether the client requested the binary fast path (`?binary=1`). */
  private readonly wantBinary: boolean;
  /** The URL actually passed to the WebSocket constructor (may carry `?binary=1`). */
  private readonly connectUrl: string;
  /** True once the server's `hello` confirmed `features.binary_frames`. */
  private binaryNegotiated = false;
  private warnedBinaryFrame = false;

  constructor(options: ChannelOptions) {
    this.options = options;
    this.hooks = options.hooks ?? {};
    this.reconnectCfg = {
      enabled: options.reconnect?.enabled ?? true,
      maxAttempts: options.reconnect?.maxAttempts ?? Infinity,
      initialBackoffMs: options.reconnect?.initialBackoffMs ?? 500,
      maxBackoffMs: options.reconnect?.maxBackoffMs ?? 30_000,
      jitter: options.reconnect?.jitter ?? 0.2,
    };
    this.helloPromise = new Promise<ChannelHello>((res, rej) => {
      this.resolveHello = res;
      this.rejectHello = rej;
    });
    this.helloPromise.catch(() => {});
    this.renewConnectionReady();
    this.isInsecureTransport = options.url.startsWith("ws://");
    this.silenceInsecureWarning = options.silenceInsecureTransportWarning === true;
    this.wantBinary = options.binary !== false;
    this.connectUrl = this.wantBinary
      ? options.url + (options.url.includes("?") ? "&" : "?") + "binary=true"
      : options.url;
    void this.connect(options);
  }

  /**
   * invoke a user hook with a try/catch so a throwing
   * callback can NEVER break the channel state machine (strand in-flight
   * streams, skip reconnect, etc.). A hook that throws gets its error
   * console.warn'd and swallowed.
   */
  private callHook<K extends keyof ChannelHooks>(
    name: K,
    arg: Parameters<NonNullable<ChannelHooks[K]>>[0],
  ): void {
    const fn = this.hooks[name] as ((a: unknown) => void) | undefined;
    if (!fn) return;
    try {
      fn(arg);
    } catch (e) {
      // eslint-disable-next-line no-console
      console.warn(
        `[the upstream curl kit SDK] channel hook '${String(name)}' threw; ignoring. ` +
          `${e instanceof Error ? e.message : String(e)}`,
      );
    }
  }

  /** Replace `connectionReady` with a fresh pending promise for the next
   * connection cycle. Called at construction and before each reconnect.
   *
   * the PREVIOUS promise must be settled, not abandoned.
   * A request issued before the first hello binds (via `whenReady()`) to the
   * then-current instance; if we just replace it, that awaiter would hang
   * forever. We reject the old one with a `SUPERSEDED` sentinel — `whenReady`
   * recognizes it and loops onto the fresh instance instead of failing. */
  private static readonly SUPERSEDED = Symbol("connectionReady-superseded");
  private renewConnectionReady(): void {
    const priorReject = this.rejectConnectionReady as
      | ((e: unknown) => void)
      | undefined;
    this.connectionReady = new Promise<void>((res, rej) => {
      this.resolveConnectionReady = res;
      this.rejectConnectionReady = rej;
    });
    // Suppress unhandled-rejection if no request is currently awaiting it.
    this.connectionReady.catch(() => {});
    if (priorReject) {
      // Settle the abandoned instance so any `whenReady()` awaiter unblocks
      // and re-targets the fresh promise (no-op if already settled).
      priorReject(CurlChannel.SUPERSEDED);
    }
  }

  /**
   * Resolve once the CURRENT connection is ready, transparently riding
   * across reconnect cycles. Each `connectionReady` either resolves (this
   * socket's hello arrived → caller may send) or rejects: with the
   * SUPERSEDED sentinel (a reconnect renewed it → loop onto the fresh one)
   * or with a real error when the channel is permanently closed (propagate).
   */
  private async whenReady(giveUp: () => boolean): Promise<void> {
    // eslint-disable-next-line no-constant-condition
    while (true) {
      // Bail if the caller no longer cares (request aborted / timed out /
      // server-cancelled → stream removed from the map). Without this an
      // aborted request on a channel in an infinite-reconnect loop would
      // keep this async frame alive forever (one leaked frame per such
      // request).
      if (giveUp()) {
        throw new ChannelError("request abandoned before send", "cancelled");
      }
      if (this.closed) {
        throw (
          this.closeError ?? new ChannelError("channel closed", "cancelled")
        );
      }
      try {
        await this.connectionReady;
        return;
      } catch (e) {
        if (e === CurlChannel.SUPERSEDED) {
          if (!this.closed) {
            // Reconnect in progress — await the renewed promise next iteration.
            continue;
          }
          // Race: a hook (e.g. onClose) called `close()` synchronously between
          // `renewConnectionReady()` and this awaiter resuming. The renewed
          // instance was then rejected with a real ChannelError by `close()`,
          // but the SYMBOL from the original instance's reject lost the race
          // to our microtask. Never propagate the sentinel to the caller —
          // translate to the channel's actual close error so `await stream.start`
          // rejects with an `Error` (SUPERSEDED-symbol escape).
          throw (
            this.closeError ?? new ChannelError("channel closed", "cancelled")
          );
        }
        throw e;
      }
    }
  }

  /** Compute backoff for the current attempt with optional jitter. */
  private nextBackoff(): number {
    const exp = Math.min(
      this.reconnectCfg.maxBackoffMs,
      this.reconnectCfg.initialBackoffMs * Math.pow(2, this.reconnectAttempt),
    );
    const j = this.reconnectCfg.jitter;
    const min = exp * (1 - j);
    const max = exp * (1 + j);
    return Math.round(min + Math.random() * (max - min));
  }

  /** Schedule the next reconnect attempt, or give up + permanently close. */
  private scheduleReconnect(): void {
    if (this.closed) return;
    if (!this.reconnectCfg.enabled) {
      this.permanentlyClose();
      return;
    }
    if (this.reconnectAttempt >= this.reconnectCfg.maxAttempts) {
      this.permanentlyClose();
      return;
    }
    const backoffMs = this.nextBackoff();
    this.reconnectAttempt += 1;
    // NOTE: connectionReady is renewed by the CALLER (handleDisconnect or the
    // connect-throw path) BEFORE this runs — and before any user hook fires —
    // so a request issued from within onClose/onReconnecting attaches to the
    // fresh pending promise. scheduleReconnect must NOT re-renew here or it
    // would abandon that hook-issued request's promise.
    this.callHook("onReconnecting", { attempt: this.reconnectAttempt, backoffMs });
    this.reconnectTimer = setTimeout(() => {
      this.reconnectTimer = undefined;
      void this.connect(this.options);
    }, backoffMs);
  }

  /** Terminal close: reconnect exhausted or disabled. Settles the once-only
   * helloPromise (reject if never connected) and the connectionReady signal. */
  private permanentlyClose(): void {
    this.closed = true;
    const err =
      this.closeError ?? new ChannelError("channel permanently closed", "internal_error");
    this.closeError = err;
    if (!this.helloSettled) {
      this.helloSettled = true;
      this.rejectHello(err);
    }
    this.rejectConnectionReady(err);
    // Reject any streams still in the map. Normally empty here (handleDisconnect
    // snapshot-rejected the pre-disconnect ones), but a request created inside
    // an onClose/onError hook during a NON-reconnecting disconnect lands in the
    // map AFTER that snapshot — without this loop it would hang forever (its
    // connectionReady.then early-returns once `this.closed` is true, and
    // nothing else settles its promises).
    for (const s of this.streams.values()) {
      s._rejectStart(err);
      s._rejectEnd(err);
      s._errorBody(err);
      s._errorEvents(err);
    }
    this.streams.clear();
  }

  private maybeWarnInsecureTransport(req: CurlRequest): void {
    if (!this.isInsecureTransport || this.warnedInsecure || this.silenceInsecureWarning) {
      return;
    }
    const hasCredential =
      !!req.bearer_token ||
      !!req.auth_password ||
      !!req.cookie ||
      !!req.session_id ||
      (!!req.headers &&
        Object.keys(req.headers).some((k) => k.toLowerCase() === "authorization"));
    if (hasCredential) {
      this.warnedInsecure = true;
      // eslint-disable-next-line no-console
      console.warn(
        "[the upstream curl kit SDK] CurlChannel URL uses ws:// (plaintext). Credential fields " +
          "(bearer_token / auth_password / cookie / session_id / Authorization header) " +
          "are about to be sent in cleartext. Use wss:// in production. " +
          "Pass `silenceInsecureTransportWarning: true` to suppress this warning.",
      );
    }
  }

  /** Static opener; awaits the WebSocket open + `hello` frame before resolving. */
  static async open(options: ChannelOptions): Promise<CurlChannel> {
    const ch = new CurlChannel(options);
    await ch.helloPromise;
    return ch;
  }

  /** Promise that resolves once the server's `hello` frame arrives. */
  ready(): Promise<ChannelHello> {
    return this.helloPromise;
  }

  /** Issue a CurlRequest. Resolves to a CurlChannelStream you can consume. */
  request(req: CurlRequest, opts: RequestOptions = {}): CurlChannelStream {
    if (this.closed) {
      // Prefer the recorded close-error when the WS dropped abnormally; if
      // the caller invoked `ch.close()` explicitly there's no closeError —
      // use "cancelled" (not "internal_error") for consistency with how
      // close() rejects existing in-flight streams.
      throw this.closeError ?? new ChannelError("channel closed by client", "cancelled");
    }
    const streamId = this.nextStreamId++;
    const sendCancel = () => {
      if (this.ws.readyState === WS_OPEN) {
        try {
          this.ws.send(JSON.stringify({ type: "request.cancel", stream_id: streamId }));
        } catch {
          /* ignore */
        }
      }
    };
    const stream = new CurlChannelStream(streamId, sendCancel);
    this.streams.set(streamId, stream);
    this.maybeWarnInsecureTransport(req);
    this.callHook("onRequestStart", {
      streamId,
      url: req.url,
      method: (req.method ?? "GET").toUpperCase(),
    });

    // Per-request timeout — independent of AbortSignal. Fires AbortError
    // through the same cancel path if no response.start arrives within the
    // window. Cleared once stream.start resolves.
    if (opts.timeoutMs !== undefined && opts.timeoutMs > 0) {
      const timer = setTimeout(() => {
        const err = createAbortError(`request timed out after ${opts.timeoutMs}ms`);
        sendCancel();
        stream._rejectStart(err);
        stream._rejectEnd(err);
        stream._errorBody(err);
        stream._errorEvents(err);
        this.streams.delete(streamId);
      }, opts.timeoutMs);
      stream.start.then(
        () => clearTimeout(timer),
        () => clearTimeout(timer),
      );
    }

    // Wire AbortSignal to server-side cancel.
    if (opts.signal) {
      if (opts.signal.aborted) {
        // Fire on next tick so caller has the stream object first.
        const reason = (opts.signal as { reason?: unknown }).reason;
        queueMicrotask(() => {
          sendCancel();
          const err = createAbortError("The operation was aborted", reason);
          stream._rejectStart(err);
          stream._rejectEnd(err);
          stream._errorBody(err);
          stream._errorEvents(err);
          this.streams.delete(streamId);
        });
      } else {
        const signal = opts.signal;
        signal.addEventListener(
          "abort",
          () => {
            // Reject the caller's promises IMMEDIATELY on abort. Previously
            // we only sent the cancel frame to the server and waited for the
            // server's `cancelled` ack to reject — but if the WS is slow,
            // dead, or the server never sends `cancelled`, the caller's
            // `await stream.start` would hang forever. Spec says fetch should
            // reject with AbortError on signal abort regardless of network.
            const reason = (signal as { reason?: unknown }).reason;
            sendCancel();
            const err = createAbortError("The operation was aborted", reason);
            stream._rejectStart(err);
            stream._rejectEnd(err);
            stream._errorBody(err);
            stream._errorEvents(err);
            this.streams.delete(streamId);
          },
          { once: true },
        );
      }
    }
    // Defer the actual send until the CURRENT connection is ready. `whenReady`
    // rides across reconnect cycles — a request issued
    // before the first hello, or mid-reconnect, transparently waits for the
    // next successful connection instead of binding to one (possibly
    // abandoned) connectionReady instance.
    void this.whenReady(() => !this.streams.has(streamId)).then(
      () => {
        // Pre-abort + deferred-send race: if the abort microtask already
        // ran (or any other path deleted this stream from the map), don't
        // bother sending — the server would see a stream_id it can't
        // associate with anything.
        if (this.closed || !this.streams.has(streamId)) return;
        // Strip `data_binary` from the JSON envelope unconditionally — the
        // server's CurlRequest has `deny_unknown_fields` and a Uint8Array
        // would JSON-serialize to a `{"0":..}` object the server rejects.
        const { data_binary, ...jsonReq } = req;
        const binBody = data_binary instanceof Uint8Array ? data_binary : null;
        if (binBody && !this.binaryNegotiated) {
          // Caller asked for a binary upload but the channel isn't on the
          // binary fast path — fail loudly rather than silently dropping it.
          const err = new ChannelError(
            "CurlRequest.data_binary requires a binary-negotiated channel " +
              "(open the channel with `binary: true` against a server that " +
              "supports binary frames)",
            "validation_error",
          );
          stream._rejectStart(err);
          stream._rejectEnd(err);
          stream._errorBody(err);
          stream._errorEvents(err);
          this.streams.delete(streamId);
          return;
        }
        try {
          this.ws.send(
            JSON.stringify(
              binBody
                ? { type: "request.start", stream_id: streamId, request: jsonReq, binary_body: true }
                : { type: "request.start", stream_id: streamId, request: jsonReq },
            ),
          );
          if (binBody) {
            // Upload body rides a separate binary frame; the server holds
            // execution until it arrives.
            this.ws.send(encodeBinFrame(BIN_KIND_REQUEST_BODY, 0, streamId, binBody));
          }
        } catch (e) {
          const err = e instanceof Error ? e : new Error(String(e));
          stream._rejectStart(err);
          stream._rejectEnd(err);
          stream._errorBody(err);
          // BUGFIX: previously omitted _errorEvents — an SSE consumer
          // parked on `events[Symbol.asyncIterator]().next()` would hang
          // forever.
          stream._errorEvents(err);
          this.streams.delete(streamId);
        }
      },
      (e) => {
        // whenReady rejected → channel permanently closed before this
        // request could be sent. (SUPERSEDED is swallowed inside whenReady.)
        stream._rejectStart(e);
        stream._rejectEnd(e);
        stream._errorBody(e);
        stream._errorEvents(e);
        this.streams.delete(streamId);
      },
    );
    return stream;
  }

  /** Close the channel (and the underlying WebSocket). */
  close(): void {
    if (this.closed) return;
    this.closed = true;
    if (this.pingTimer !== undefined) clearInterval(this.pingTimer);
    if (this.reconnectTimer !== undefined) {
      clearTimeout(this.reconnectTimer);
      this.reconnectTimer = undefined;
    }
    try {
      if (this.ws) this.ws.close();
    } catch {
      /* ignore */
    }
    const err = new ChannelError("channel closed by client", "cancelled");
    this.closeError = err;
    for (const s of this.streams.values()) {
      s._rejectStart(err);
      s._rejectEnd(err);
      s._errorBody(err);
      s._errorEvents(err);
    }
    this.streams.clear();
    // Settle both readiness promises so anything awaiting open()/ready() or a
    // deferred request send rejects instead of hanging.
    if (!this.helloSettled) {
      this.helloSettled = true;
      this.rejectHello(err);
    }
    this.rejectConnectionReady(err);
  }

  // ---------- internals -----------------------------------------------

  private async connect(options: ChannelOptions): Promise<void> {
    // close() may have run between scheduleReconnect's
    // setTimeout being scheduled and this callback firing. Don't open a
    // stray socket on a closed channel.
    if (this.closed) return;
    let ws: WsLike;
    try {
      ws = await openWebSocket(this.connectUrl);
    } catch (e) {
      const err = e instanceof Error ? e : new Error(String(e));
      this.callHook("onError", err);
      // a throwing openWebSocket (bad URL, missing `ws`
      // dep, transient transport-construction failure) on a SCHEDULED
      // reconnect must not silently kill the retry loop. If reconnect is
      // viable, schedule the next attempt; otherwise terminate cleanly so
      // request() throws instead of wedging forever.
      this.closeError = err;
      const willReconnect =
        !this.closed &&
        this.reconnectCfg.enabled &&
        this.reconnectAttempt < this.reconnectCfg.maxAttempts;
      if (willReconnect) {
        // in-flight streams MUST ride the upcoming
        // reconnect — they're already attached to `connectionReady` via
        // `whenReady()`, which loops onto the renewed instance after
        // SUPERSEDED. Renew BEFORE scheduleReconnect (which no longer renews);
        // do NOT reject/clear the queued streams here, or pre-hello requests
        // would fail spuriously on every transient transport-construction
        // hiccup instead of waiting for a later successful socket.
        this.renewConnectionReady();
        this.scheduleReconnect();
      } else {
        // Terminal: reject any in-flight streams (e.g. `new CurlChannel().request()`
        // issued before the first hello with reconnect disabled or attempts
        // exhausted) so they surface the error instead of hanging. Snapshot +
        // clear before permanentlyClose so its leftover-reject loop is a no-op
        // for these, and to mirror handleDisconnect's snapshot ordering.
        const inflight = [...this.streams.values()];
        this.streams.clear();
        for (const s of inflight) {
          s._rejectStart(err);
          s._rejectEnd(err);
          s._errorBody(err);
          s._errorEvents(err);
        }
        this.permanentlyClose();
      }
      return;
    }
    // close() may have run DURING `await openWebSocket()`.
    // The pre-await `if (this.closed)` guard can't catch that. Re-check
    // here and tear down the just-created socket instead of attaching
    // listeners + timers to a socket the caller already abandoned.
    if (this.closed) {
      // the Node `ws` package is an EventEmitter — calling
      // `.close()` on a still-CONNECTING socket that then fails emits an
      // 'error' event; with NO 'error' listener attached, EventEmitter
      // RE-THROWS it as an uncaught exception (crashing the process). The
      // surrounding try/catch does NOT catch that async emit. Attach a
      // no-op error listener FIRST so the failure is swallowed. (undici's
      // WebSocket doesn't throw on listenerless error, but the listener is
      // harmless there.)
      try {
        ws.addEventListener("error", () => {});
      } catch {
        /* some impls reject addEventListener post-close; ignore */
      }
      try {
        ws.close();
      } catch {
        /* ignore */
      }
      return;
    }
    this.ws = ws;
    // Per-connection generation token. A late `hello` (or any frame) from a
    // socket that already passed through handleDisconnect must be ignored —
    // otherwise a delayed hello from socket N could resolve readiness after
    // we've already moved to socket N+1. The message
    // listener captures `ws` and bails if `this.ws !== ws`.
    const myWs = ws;
    const helloTimeout = options.helloTimeoutMs ?? 10_000;

    // `handleDisconnect` is defined BEFORE the helloTimer so the timer can
    // invoke it DIRECTLY rather than relying on `ws.close()` producing a
    // `close`/`error` event — which it does not on an already-dead socket
    // (undici drops the events that fired during the `await openWebSocket()`
    // microtask gap, before these listeners were attached). `disconnected`
    // makes this idempotent across the timer + close + error + watchdog
    // entry points.
    let disconnected = false;
    let helloTimer: ReturnType<typeof setTimeout>;
    const handleDisconnect = (code: number, reason: string): void => {
      if (disconnected) return;
      disconnected = true;
      clearTimeout(helloTimer);
      const err = new ChannelError(
        `WebSocket closed (code ${code}): ${reason || "no reason"}`,
        "internal_error",
      );
      const willReconnect =
        !this.closed &&
        this.reconnectCfg.enabled &&
        this.reconnectAttempt < this.reconnectCfg.maxAttempts;
      // do NOT clobber a client-initiated close error.
      // close() already set this.closed + this.closeError ("channel closed
      // by client", "cancelled"); the subsequent ws.close() fires a close
      // event into here. Overwriting closeError with the generic "WebSocket
      // closed" would mislead a later request()'s rejection reason.
      if (!this.closed) {
        this.closeError = err;
      }
      if (this.pingTimer !== undefined) clearInterval(this.pingTimer);
      // renew connectionReady BEFORE firing user hooks. A
      // user's onClose/onError handler may synchronously call
      // channel.request(); that request must attach to the FRESH (pending)
      // connectionReady — not the stale resolved one from the dead socket.
      if (willReconnect) {
        this.renewConnectionReady();
      }
      // snapshot the genuinely in-flight streams (the
      // ones that existed BEFORE this disconnect) and clear the map BEFORE
      // firing user hooks. If we rejected `this.streams` AFTER the hooks, a
      // request created inside onClose/onError would be added to the map and
      // then immediately rejected by that loop — so a hook-issued request
      // could never survive into the reconnect. By snapshotting first, the
      // hook-created stream lands in the now-empty map, attached to the
      // fresh connectionReady, and (on willReconnect) rides the new socket.
      const inflight = [...this.streams.values()];
      this.streams.clear();
      this.callHook("onClose", { code, reason: reason || "", willReconnect });
      this.callHook("onError", err);
      for (const s of inflight) {
        s._rejectStart(err);
        s._rejectEnd(err);
        s._errorBody(err);
        s._errorEvents(err);
      }
      if (willReconnect) {
        this.scheduleReconnect();
      } else {
        // No reconnect coming: permanentlyClose rejects connectionReady AND
        // any streams a hook just created (they'd otherwise hang, since
        // their connectionReady.then early-returns on `this.closed`).
        this.permanentlyClose();
      }
    };

    helloTimer = setTimeout(() => {
      // hello timed out (or the connection silently died and we never saw an
      // event). Drive the disconnect path DIRECTLY — do not depend on a
      // close/error event from ws.close().
      try {
        ws.close();
      } catch {
        /* */
      }
      handleDisconnect(1006, "timed out waiting for hello frame");
    }, helloTimeout);

    // Watchdog for the lost-event race: undici can fire `error` during the
    // `await openWebSocket()` gap, before the listeners below were attached,
    // leaving the socket CLOSED with no event ever delivered. A microtask +
    // macrotask check catches that and shortens the dead time from
    // `helloTimeout` to ~0.
    const readyStateWatchdog = setTimeout(() => {
      // 3 = CLOSED, 2 = CLOSING per the WebSocket spec.
      if (!disconnected && (ws.readyState === 3 || ws.readyState === 2)) {
        handleDisconnect(1006, "connection failed before listeners attached");
      }
    }, 0);
    // Don't let the watchdog keep a Node process alive on its own.
    (readyStateWatchdog as unknown as { unref?: () => void }).unref?.();

    ws.addEventListener("open", () => {
      // Server sends `hello` proactively on open; nothing to do here.
    });
    ws.addEventListener("message", (ev) => {
      // ignore frames from a socket that's already been
      // superseded (late/stale `hello` or data arriving after we moved to a
      // newer connection). `disconnected` covers same-socket teardown;
      // `this.ws !== myWs` covers the reconnected-to-a-new-socket case.
      if (disconnected || this.ws !== myWs) return;
      // Binary frames carry response body chunks on a binary-negotiated
      // channel. JSON control/data messages always arrive as text frames.
      if (typeof ev.data !== "string") {
        if (this.binaryNegotiated) {
          this.handleBinaryFrame(ev.data);
          return;
        }
        // Legacy fallback: a server that never negotiated binary should not
        // be sending binary frames — but if one does (or an old runtime
        // delivers a text frame as bytes), decode as UTF-8 JSON.
        let decoded: string;
        try {
          decoded = SHARED_TEXT_DECODER.decode(ev.data as ArrayBufferLike);
        } catch {
          return;
        }
        if (decoded.length > MAX_INBOUND_FRAME_BYTES) {
          this.closeForOversizeFrame(ws);
          return;
        }
        let p: ChannelServerMessage;
        try {
          p = JSON.parse(decoded);
        } catch {
          return;
        }
        this.handleServerMessage(p, helloTimer);
        return;
      }
      const text: string = ev.data;
      // DoS guard: a hostile server could send a huge JSON payload that ties
      // up the parser. Reject anything above MAX_INBOUND_FRAME_BYTES (the
      // server's own hello.limits.max_frame_bytes is typically 1 MiB but we
      // accept up to 16 MiB at the SDK boundary).
      if (text.length > MAX_INBOUND_FRAME_BYTES) {
        this.closeForOversizeFrame(ws);
        return;
      }
      let parsed: ChannelServerMessage;
      try {
        parsed = JSON.parse(text);
      } catch {
        return;
      }
      this.handleServerMessage(parsed, helloTimer);
    });
    // `close` and `error` both route to the single handleDisconnect defined
    // above (before helloTimer). undici's global WebSocket fires ONLY `error`
    // (never `close`) on a connection-level failure; Node `ws` fires `error`
    // then `close`. The `disconnected` guard makes this idempotent across the
    // close + error + helloTimer + watchdog entry points.
    ws.addEventListener("close", (ev) => {
      handleDisconnect(ev.code, ev.reason);
    });
    ws.addEventListener("error", () => {
      // undici fires `error` with no useful payload and NO subsequent
      // `close`. Synthesize a 1006 (abnormal closure) disconnect. If a
      // `close` does follow (Node `ws`), the `disconnected` guard makes it
      // a no-op.
      handleDisconnect(1006, "connection error");
    });

    const pingInterval = options.pingIntervalMs ?? 25_000;
    if (pingInterval > 0) {
      this.pingTimer = setInterval(() => {
        if (this.ws.readyState === WS_OPEN) {
          try {
            this.ws.send(JSON.stringify({ type: "ping" }));
          } catch {
            /* ignore */
          }
        }
      }, pingInterval);
    }
  }

  /** Tear down the connection when an inbound frame exceeds the SDK's hard cap. */
  private closeForOversizeFrame(ws: WsLike): void {
    const err = new ChannelError(
      `inbound WS frame exceeded ${MAX_INBOUND_FRAME_BYTES} bytes`,
      "internal_error",
    );
    this.closeError = err;
    try {
      ws.close(1009, "frame too large");
    } catch {
      /* ignore */
    }
  }

  private warnBinaryFrameOnce(reason: string): void {
    if (this.warnedBinaryFrame) return;
    this.warnedBinaryFrame = true;
    // eslint-disable-next-line no-console
    console.warn(`[the upstream curl kit SDK] ${reason}; binary frame ignored.`);
  }

  /** Normalize an inbound binary WS payload to bytes, then route it.
   *
   * The transport forces `binaryType = "arraybuffer"`, so frames arrive
   * synchronously as `ArrayBuffer` (or a view). A `Blob` is NOT handled: its
   * `arrayBuffer()` is async, and a `response.end` frame arriving in the
   * meantime would close the stream before the chunk could be routed —
   * silently dropping body bytes. If a runtime ever delivers a Blob despite
   * the `binaryType` request, we warn rather than corrupt the body. */
  private handleBinaryFrame(data: unknown): void {
    if (data instanceof ArrayBuffer) {
      this.routeBinaryFrame(new Uint8Array(data));
    } else if (ArrayBuffer.isView(data)) {
      const v = data as ArrayBufferView;
      this.routeBinaryFrame(new Uint8Array(v.buffer, v.byteOffset, v.byteLength));
    } else {
      this.warnBinaryFrameOnce(
        "binary frame arrived in an unexpected form (expected ArrayBuffer)",
      );
    }
  }

  /** Decode a 16-byte binary frame header and hand the payload to its stream. */
  private routeBinaryFrame(bytes: Uint8Array): void {
    if (bytes.byteLength > MAX_INBOUND_FRAME_BYTES) {
      if (this.ws) this.closeForOversizeFrame(this.ws);
      return;
    }
    if (bytes.byteLength < BIN_FRAME_HEADER_LEN || bytes[0] !== BIN_FRAME_VERSION) {
      this.warnBinaryFrameOnce("malformed or unversioned binary frame");
      return;
    }
    const kind = bytes[1]!;
    if (kind !== BIN_KIND_BODY) {
      this.warnBinaryFrameOnce(`unexpected binary frame kind ${kind}`);
      return;
    }
    // Decode the little-endian u64 stream_id with direct byte ops — no
    // DataView allocation and no BigInt on this per-frame hot path. Stream
    // ids are assigned sequentially from 1 so the high word is effectively
    // always 0, but it is still folded in for correctness.
    const lo =
      (bytes[8]! | (bytes[9]! << 8) | (bytes[10]! << 16) | (bytes[11]! << 24)) >>> 0;
    const hi =
      (bytes[12]! | (bytes[13]! << 8) | (bytes[14]! << 16) | (bytes[15]! << 24)) >>> 0;
    const streamId = hi === 0 ? lo : hi * 0x1_0000_0000 + lo;
    const stream = this.streams.get(streamId);
    // No stream → already finished, cancelled, or unknown id: drop the chunk.
    if (!stream) return;
    stream._enqueueBodyChunk(bytes.subarray(BIN_FRAME_HEADER_LEN));
  }

  private handleServerMessage(msg: ChannelServerMessage, helloTimer: ReturnType<typeof setTimeout>): void {
    switch (msg.type) {
      case "hello": {
        clearTimeout(helloTimer);
        // Forward-compat: this SDK speaks channel protocol version 2. A
        // future server bumping to v3 with a breaking change would
        // otherwise be silently accepted. Warn on unknown versions but
        // don't refuse — the server is free to add backward-compatible
        // additions within v2 (we already handle unknown JSON fields).
        if (msg.version !== 2) {
          // eslint-disable-next-line no-console
          console.warn(
            `[the upstream curl kit SDK] CurlChannel hello version ${msg.version} is not the ` +
              `version this SDK was built against (2). Behavior may diverge.`,
          );
        }
        const hello: ChannelHello = {
          version: msg.version,
          connection_id: msg.connection_id,
          limits: msg.limits,
          features: msg.features,
        };
        this.hello = hello;
        // Binary fast path is active only if we asked for it AND the server
        // confirmed support. Re-evaluated on every (re)connect.
        this.binaryNegotiated =
          this.wantBinary && hello.features?.binary_frames === true;
        this.reconnectAttempt = 0; // successful connect resets backoff
        // Once-only: the first-ever hello settles helloPromise (open/ready).
        if (!this.helloSettled) {
          this.helloSettled = true;
          this.resolveHello(hello);
        }
        // Per-connection: every hello (initial + each reconnect) resolves
        // the current connectionReady so queued requests' deferred sends fire.
        this.resolveConnectionReady();
        this.callHook("onOpen", hello);
        return;
      }
      case "pong":
        return;
      case "accepted":
        // Server acknowledged registration. No state transition needed today;
        // the per-stream promises bind to response.start/end. If the stream
        // is unknown (e.g., we cancelled before the ack arrived), drop silently.
        return;
      case "cancelled": {
        const s = this.streams.get((msg as CancelledMessage).stream_id);
        if (s) {
          const err = createAbortError("cancelled by server");
          s._rejectStart(err);
          s._rejectEnd(err);
          s._errorBody(err);
          s._errorEvents(err);
          this.streams.delete(s._streamId);
        }
        return;
      }
      case "response.start": {
        const m = msg as ResponseStartMessage;
        const s = this.streams.get(m.stream_id);
        if (s) {
          s._resolveStart(m);
          this.callHook("onResponseStart", {
            streamId: m.stream_id,
            status: m.status_code,
            isSse: m.is_sse === true,
          });
        }
        return;
      }
      case "response.body": {
        const m = msg as ResponseBodyMessage;
        const s = this.streams.get(m.stream_id);
        if (!s) return;
        const bytes = base64Decode(m.data);
        s._enqueueBodyChunk(bytes);
        return;
      }
      case "response.sse_event": {
        const m = msg as ResponseSseEventMessage;
        const s = this.streams.get(m.stream_id);
        if (!s) return;
        const ev: SseEvent = {
          event: m.event,
          data: m.data,
          seq: m.seq,
        };
        if (m.id !== undefined) ev.id = m.id;
        if (m.retry !== undefined) ev.retry = m.retry;
        if (m.data_truncated) ev.truncated = true;
        s._enqueueSseEvent(ev);
        return;
      }
      case "response.end": {
        const m = msg as ResponseEndMessage;
        const s = this.streams.get(m.stream_id);
        if (s) {
          // CRITICAL ordering: close both body AND events streams BEFORE
          // resolving end. Previously _closeEvents was wired via
          // `this.end.then(onEnd)` which scheduled a microtask AFTER
          // `_resolveEnd`, leaving a window where a consumer that awaited
          // `end` and then iterated `events` would push a waiter to a queue
          // that wouldn't be drained until the next microtask.
          s._closeBody();
          s._closeEvents();
          s._resolveEnd(m);
          this.streams.delete(m.stream_id);
          this.callHook("onResponseEnd", {
            streamId: m.stream_id,
            totalBytes: m.metadata.size_download,
            ...(m.sse_events !== undefined ? { sseEvents: m.sse_events } : {}),
          });
        }
        return;
      }
      case "error": {
        const m = msg as ErrorMessage;
        const err = new ChannelError(m.message, m.error_type, m.stream_id);
        if (m.stream_id !== undefined) {
          const s = this.streams.get(m.stream_id);
          if (s) {
            s._rejectStart(err);
            s._rejectEnd(err);
            s._errorBody(err);
            s._errorEvents(err);
            this.streams.delete(m.stream_id);
          }
        } else {
          // Connection-level error: fail all in-flight.
          for (const s of this.streams.values()) {
            s._rejectStart(err);
            s._rejectEnd(err);
            s._errorBody(err);
            s._errorEvents(err);
          }
          this.streams.clear();
        }
        return;
      }
      default: {
        // Unknown variant — likely a future-version frame. Warn once per
        // unknown type so a v3 server addition doesn't go silently
        // unhandled (would have produced hangs / stale state otherwise).
        const unknownType = (msg as { type?: unknown }).type;
        if (!this.warnedUnknownTypes.has(String(unknownType))) {
          this.warnedUnknownTypes.add(String(unknownType));
          // eslint-disable-next-line no-console
          console.warn(
            `[the upstream curl kit SDK] Unknown channel message type: ${String(unknownType)}. ` +
              `Server may be on a newer protocol version. Frame ignored.`,
          );
        }
        return;
      }
    }
  }
}

function base64Decode(s: string): Uint8Array {
  // Node/Bun: `Buffer.from(s, "base64")` is a native C++ decode — far faster
  // than `atob()` + a per-char JS loop. Prefer it whenever a global Buffer
  // exists; fall back to atob in the browser.
  const B = (globalThis as { Buffer?: typeof Buffer }).Buffer;
  if (typeof B !== "undefined") {
    const buf = B.from(s, "base64");
    return new Uint8Array(buf.buffer, buf.byteOffset, buf.byteLength);
  }
  const bin = atob(s);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}


// ════════════════════════════════════════════════════════════════════════
// VENDORED: fetch.ts
// ════════════════════════════════════════════════════════════════════════

// fetch() drop-in that routes through a the upstream curl kit channel WebSocket.
//
// The returned function is signature-compatible with the global `fetch`:
//   const fetch = createCurlFetch({ channelUrl: 'wss://.../api/v1/curl/channel' });
//   const res = await fetch('https://api.example.com/v1/things', { method: 'POST', body: '{}' });
//   const text = await res.text();
//
// SSE responses (Content-Type: text/event-stream) come back as a Response with
// a streaming body — the body's ReadableStream yields raw SSE-formatted bytes
// just like the upstream sent them, so `EventSource`-style clients can consume
// directly via res.body. The companion `CurlChannel` low-level API exposes a typed
// `SseEvent` iterator for callers who prefer parsed events.

/** Configuration for `createCurlFetch`. */
export interface CurlFetchOptions extends ChannelOptions {
  /**
   * Pre-existing channel to reuse instead of opening a new one. When set, the
   * `url` field is still required by ChannelOptions but ignored.
   */
  channel?: CurlChannel;
  /**
   * Override how fetch() converts upstream SSE responses. Default `"stream"`
   * returns a Response with a streaming body of raw SSE bytes (fetch-compatible
   * with EventSource/`res.body.getReader()`). Pass `"buffered"` to instead wait
   * for the entire SSE stream to complete and return the joined bytes (rare;
   * mostly for testing).
   */
  sseMode?: "stream" | "buffered";
  /**
   * Default options merged into every CurlRequest. Useful for setting things
   * like `session_id`, `bearer_token`, `user_agent` once. Per-call init
   * always wins.
   */
  defaults?: Partial<CurlRequest>;
  /**
   * Compress the REQUEST body before sending. `"gzip"` runs the body
   * through `CompressionStream("gzip")` and sets `Content-Encoding: gzip`
   * on the upstream request; the relay passes the bytes verbatim, so the
   * upstream sees compressed bytes and is responsible for decompression
   * (most modern servers handle it transparently when the body is large
   * enough to matter).
   *
   * Default: `"none"`. Opt-in only — auto-gzipping every body would
   * silently break upstreams that don't accept Content-Encoding on
   * requests.
   */
  requestEncoding?: "gzip" | "none";
}

/** The fetch-compatible function returned by `createCurlFetch`. */
export type CurlFetch = (
  input: string | URL | Request,
  init?: RequestInit,
) => Promise<Response>;

/** Build a fetch-shaped function bound to a the upstream curl kit channel. */
export function createCurlFetch(options: CurlFetchOptions): CurlFetch {
  let channel: CurlChannel | null = options.channel ?? null;
  let openPromise: Promise<CurlChannel> | null = null;
  const sseMode = options.sseMode ?? "stream";
  const defaults = options.defaults ?? {};
  const requestEncoding = options.requestEncoding ?? "none";

  const getChannel = async (): Promise<CurlChannel> => {
    if (channel) return channel;
    if (!openPromise) openPromise = CurlChannel.open(options);
    channel = await openPromise;
    return channel;
  };

  return async function fetch(
    input: string | URL | Request,
    init: RequestInit = {},
  ): Promise<Response> {
    const ch = await getChannel();
    const req = await buildCurlRequest(input, init, defaults);
    if (requestEncoding === "gzip") {
      await applyRequestGzip(req);
    }

    // Precedence per fetch spec: init.signal overrides input.signal when
    // input is a Request. If neither is set, no abort signal is wired.
    const requestOpts: RequestOptions = {};
    const inputSignal =
      typeof input === "object" && input !== null && "signal" in input && input instanceof Request
        ? (input as Request).signal
        : undefined;
    const signal = init.signal ?? inputSignal;
    if (signal) requestOpts.signal = signal;

    const stream = ch.request(req, requestOpts);

    try {
      const start = await stream.start;
      // `redirect: 'error'` → throw on any 3xx, per fetch spec.
      // Use the effective redirect mode (input + init merged), not just init.
      const inputRedirect =
        typeof input === "object" && input !== null && input instanceof Request
          ? input.redirect
          : undefined;
      const effectiveRedirect = init.redirect ?? inputRedirect;
      if (effectiveRedirect === "error" && start.status_code >= 300 && start.status_code < 400) {
        stream.cancel();
        throw new TypeError(
          `fetch: redirect: 'error' but upstream returned ${start.status_code}`,
        );
      }
      return buildResponse(start, stream, sseMode);
    } catch (e) {
      // start failed → map to a useful Error.
      if (e instanceof ChannelError && e.errorType === "cancelled") {
        throw createAbortError(e.message);
      }
      throw e;
    }
  };
}

async function buildCurlRequest(
  input: string | URL | Request,
  init: RequestInit,
  defaults: Partial<CurlRequest>,
): Promise<CurlRequest> {
  // Resolve URL + extract any prebuilt headers/method/body from `input` when
  // it's a `Request`. Per-call `init` overrides `input` per fetch spec.
  let url: string;
  let method = init.method;
  const inboundHeaders = new Headers();
  let body: BodyInit | null = null;

  if (input instanceof URL) {
    url = input.toString();
  } else if (typeof input === "string") {
    url = input;
  } else {
    // Request — guard against double-consumption by cloning first. Without
    // clone(), reading .body locks the source Request and any caller that
    // retries with the same Request object gets an opaque runtime TypeError.
    if (input.bodyUsed) {
      throw new TypeError(
        "hoody-sdk: Request body has already been consumed. " +
          "Pass `init` directly or clone the Request before reuse.",
      );
    }
    const req = input.clone();
    url = req.url;
    if (!method) method = req.method;
    req.headers.forEach((v, k) => inboundHeaders.set(k, v));
    body = req.body;
  }

  if (init.headers) {
    const h = new Headers(init.headers);
    h.forEach((v, k) => inboundHeaders.set(k, v));
  }
  // BUGFIX: per WHATWG fetch §5.1
  // step 34, `init.body` being PRESENT (even as null) MUST replace the input
  // body. The old `init.body !== null` guard meant `{ body: null }` was a
  // no-op — callers couldn't strip a Request body.
  if ("body" in init) {
    body = (init.body ?? null) as BodyInit | null;
  }
  if (!method) method = "GET";

  const headers: Record<string, string> = {};
  inboundHeaders.forEach((v, k) => {
    const lk = k.toLowerCase();
    // Skip hop-by-hop / proxy-managed headers. Forward Content-Type for ANY
    // body type (was previously gated on `typeof body === 'string'`, which
    // dropped caller-set Content-Type for binary/blob bodies).
    if (lk === "host" || lk === "content-length" || lk === "connection") return;
    headers[k] = v;
  });

  const req: CurlRequest = {
    ...defaults,
    url,
    method: method.toUpperCase(),
  };
  if (Object.keys(headers).length > 0) {
    req.headers = { ...(defaults.headers ?? {}), ...headers };
  }

  // Honor fetch's `init.redirect`: 'follow' (default), 'manual' (don't follow,
  // return the 3xx), 'error' (throw a TypeError on any 3xx). Server-side
  // follow_redirects=false achieves 'manual'; 'error' is implemented client-side
  // in buildResponse via the status range check.
  //
  // BUGFIX: when input is a `Request` object,
  // `init.redirect` falls back to `input.redirect`. Previously the SDK only
  // read `init.redirect`, so `fetch(new Request(url, { redirect: "manual" }))`
  // lost the redirect mode.
  const inputRedirect =
    typeof input === "object" && input !== null && input instanceof Request
      ? input.redirect
      : undefined;
  const effectiveRedirect = init.redirect ?? inputRedirect;
  if (effectiveRedirect === "manual" || effectiveRedirect === "error") {
    req.follow_redirects = false;
    req.max_redirects = 0;
  }

  if (body !== null && body !== undefined) {
    const resolved = await bodyToData(body);
    if ("data" in resolved) {
      req.data = resolved.data;
    } else {
      // Binary body → uploaded as a binary WebSocket frame (channel must be
      // binary-negotiated; `CurlChannel.request()` rejects clearly otherwise).
      req.data_binary = resolved.data_binary;
    }
  }
  return req;
}

/**
 * Compress the request body in place. The body is moved from `req.data` /
 * `req.data_binary` to `req.data_binary` (the gzipped bytes are always
 * binary). A `Content-Encoding: gzip` header is added — caller's existing
 * value is preserved if already set to gzip; mismatches throw.
 *
 * No-op when the request has no body. The relay does not touch the bytes
 * (libcurl passes them verbatim), so the UPSTREAM is responsible for
 * decompressing.
 */
async function applyRequestGzip(req: CurlRequest): Promise<void> {
  let raw: Uint8Array | null = null;
  if (req.data_binary instanceof Uint8Array && req.data_binary.byteLength > 0) {
    raw = req.data_binary;
  } else if (typeof req.data === "string" && req.data.length > 0) {
    raw = new TextEncoder().encode(req.data);
  }
  if (raw === null) return;

  const compressed = await gzipBytes(raw);
  delete req.data;
  req.data_binary = compressed;

  const headers: Record<string, string> = { ...(req.headers ?? {}) };
  let found: string | undefined;
  for (const k of Object.keys(headers)) {
    if (k.toLowerCase() === "content-encoding") {
      found = headers[k];
      delete headers[k];
    }
  }
  if (found !== undefined && found.toLowerCase() !== "gzip") {
    throw new TypeError(
      `hoody-sdk: requestEncoding="gzip" conflicts with caller-set Content-Encoding: ${found}`,
    );
  }
  headers["Content-Encoding"] = "gzip";
  req.headers = headers;
}

/** Run `bytes` through the platform's CompressionStream("gzip"). */
async function gzipBytes(bytes: Uint8Array): Promise<Uint8Array> {
  // Copy into a fresh ArrayBuffer so the type matches BufferSource exactly
  // (Uint8Array<SharedArrayBuffer> is not assignable to BufferSource on TS
  // strict targets).
  const ab = new ArrayBuffer(bytes.byteLength);
  new Uint8Array(ab).set(bytes);
  const cs = new CompressionStream("gzip");
  const writer = cs.writable.getWriter();
  void writer.write(new Uint8Array(ab));
  void writer.close();
  const reader = cs.readable.getReader();
  const chunks: Uint8Array[] = [];
  while (true) {
    const { value, done } = await reader.read();
    if (done) break;
    if (value) chunks.push(value);
  }
  return concat(chunks);
}

/** A request body resolved either to the JSON `data` string field or to the
 * binary `data_binary` upload path. */
type ResolvedBody = { data: string } | { data_binary: Uint8Array };

/**
 * Convert a BodyInit to either a UTF-8 `data` string or a `data_binary` byte
 * payload. String-shaped bodies (string, URLSearchParams, FormData-without-
 * File) map to `data`. Byte-shaped bodies (ArrayBuffer/ArrayBufferView/Blob/
 * ReadableStream) are probed: valid UTF-8 stays on the `data` text path (so a
 * text body wrapped in a `Request` — whose `.body` is always a ReadableStream
 * — keeps working on a text-only channel); genuinely binary content maps to
 * `data_binary` and uploads as a raw binary WebSocket frame.
 *
 * Rejected with TypeError: FormData containing File entries (cannot be
 * represented over `CurlRequest`); any non-standard BodyInit.
 */
async function bodyToData(body: BodyInit): Promise<ResolvedBody> {
  if (typeof body === "string") return { data: body };
  if (body instanceof URLSearchParams) return { data: body.toString() };
  if (body instanceof FormData) {
    // FormData with File entries can't be represented over CurlRequest. Reject
    // loudly rather than silently dropping file contents to filename strings.
    let hasFile = false;
    body.forEach((v) => {
      if (typeof v !== "string") hasFile = true;
    });
    if (hasFile) {
      throw new TypeError(
        "hoody-sdk: FormData with File entries is not supported. " +
          "Use `form: {...}` on the CurlRequest directly (string fields only), " +
          "or pass the file bytes as a Blob/Uint8Array body with an explicit " +
          "Content-Type header.",
      );
    }
    const params = new URLSearchParams();
    body.forEach((v, k) => params.append(k, v as string));
    return { data: params.toString() };
  }

  // Byte-shaped bodies: collect into a single owned Uint8Array.
  let bytes: Uint8Array;
  if (body instanceof ArrayBuffer) {
    bytes = new Uint8Array(body.slice(0));
  } else if (ArrayBuffer.isView(body)) {
    // Copy out of the caller's buffer so a later mutation can't corrupt the
    // in-flight upload.
    bytes = new Uint8Array(
      body.buffer.slice(body.byteOffset, body.byteOffset + body.byteLength),
    );
  } else if (body instanceof Blob) {
    bytes = new Uint8Array(await body.arrayBuffer());
  } else if (body instanceof ReadableStream) {
    const reader = body.getReader();
    const chunks: Uint8Array[] = [];
    // eslint-disable-next-line no-constant-condition
    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      chunks.push(value as Uint8Array);
    }
    bytes = concat(chunks);
  } else {
    // Reject any non-standard BodyInit explicitly rather than silently
    // coercing to "[object Object]" via String(body).
    throw new TypeError(
      "hoody-sdk: unsupported request body type. Pass string, " +
        "URLSearchParams, ArrayBuffer/Uint8Array/Blob/ReadableStream, or " +
        "FormData without File entries.",
    );
  }

  // Prefer the text `data` path when the bytes decode cleanly as UTF-8 — that
  // keeps the request on the text protocol (no binary-negotiated channel
  // required). Non-UTF-8 content falls through to the binary upload path.
  const asText = tryDecodeUtf8(bytes);
  return asText !== null ? { data: asText } : { data_binary: bytes };
}

/** Strict UTF-8 decode; returns `null` on any invalid byte sequence. */
function tryDecodeUtf8(bytes: Uint8Array): string | null {
  try {
    return new TextDecoder("utf-8", { fatal: true }).decode(bytes);
  } catch {
    return null;
  }
}

function concat(chunks: Uint8Array[]): Uint8Array {
  const total = chunks.reduce((n, c) => n + c.length, 0);
  const out = new Uint8Array(total);
  let pos = 0;
  for (const c of chunks) {
    out.set(c, pos);
    pos += c.length;
  }
  return out;
}

/**
 * HTTP status code → standard reason phrase, per RFC 9110 §15. Used to
 * synthesize `Response.statusText` since the channel protocol doesn't carry
 * the upstream's reason phrase.
 */
const HTTP_STATUS_TEXT: Record<number, string> = {
  100: "Continue", 101: "Switching Protocols", 102: "Processing", 103: "Early Hints",
  200: "OK", 201: "Created", 202: "Accepted", 203: "Non-Authoritative Information",
  204: "No Content", 205: "Reset Content", 206: "Partial Content", 207: "Multi-Status",
  208: "Already Reported", 226: "IM Used",
  300: "Multiple Choices", 301: "Moved Permanently", 302: "Found", 303: "See Other",
  304: "Not Modified", 305: "Use Proxy", 307: "Temporary Redirect", 308: "Permanent Redirect",
  400: "Bad Request", 401: "Unauthorized", 402: "Payment Required", 403: "Forbidden",
  404: "Not Found", 405: "Method Not Allowed", 406: "Not Acceptable",
  407: "Proxy Authentication Required", 408: "Request Timeout", 409: "Conflict",
  410: "Gone", 411: "Length Required", 412: "Precondition Failed",
  413: "Content Too Large", 414: "URI Too Long", 415: "Unsupported Media Type",
  416: "Range Not Satisfiable", 417: "Expectation Failed", 418: "I'm a teapot",
  421: "Misdirected Request", 422: "Unprocessable Content", 423: "Locked",
  424: "Failed Dependency", 425: "Too Early", 426: "Upgrade Required",
  428: "Precondition Required", 429: "Too Many Requests",
  431: "Request Header Fields Too Large", 451: "Unavailable For Legal Reasons",
  500: "Internal Server Error", 501: "Not Implemented", 502: "Bad Gateway",
  503: "Service Unavailable", 504: "Gateway Timeout",
  505: "HTTP Version Not Supported", 506: "Variant Also Negotiates",
  507: "Insufficient Storage", 508: "Loop Detected", 510: "Not Extended",
  511: "Network Authentication Required",
};

function buildResponse(
  start: Awaited<CurlChannelStream["start"]>,
  stream: CurlChannelStream,
  sseMode: "stream" | "buffered",
): Response {
  const headers = new Headers();
  for (const h of start.raw_headers) {
    try {
      headers.append(h.name, h.value);
    } catch {
      // Skip invalid header values.
    }
  }

  // Synthesize statusText from the standard reason-phrase table since the
  // channel protocol doesn't forward the upstream's reason phrase. Falls back
  // to empty string for non-standard codes (Response constructor's default).
  const statusText = HTTP_STATUS_TEXT[start.status_code] ?? "";

  // Per fetch spec, Response.url MUST be the (post-redirect) effective URL,
  // and Response.type should be "basic" for same-origin and "cors"/"opaque"
  // depending on the request. We're a proxy — every response is effectively
  // "basic" from our client's POV (no CORS preflight, no opaque). Both are
  // set via defineProperty since Response constructor doesn't expose them.
  let warnedSealedResponse = false;
  const finalize = (r: Response): Response => {
    const fields: Array<[string, unknown]> = [
      ["url", start.effective_url || ""],
      ["type", "basic"],
    ];
    for (const [name, value] of fields) {
      try {
        Object.defineProperty(r, name, {
          value,
          configurable: false,
          writable: false,
        });
      } catch (e) {
        if (!warnedSealedResponse) {
          warnedSealedResponse = true;
          // eslint-disable-next-line no-console
          console.warn(
            `[the upstream curl kit SDK] Response.${name} cannot be set on this runtime ` +
              `(sealed Response: ${e instanceof Error ? e.message : String(e)}). ` +
              "Some Response getters will return runtime defaults. Read " +
              "start.effective_url via the low-level CurlChannel.request() API if " +
              "you need the canonical URL.",
          );
        }
      }
    }
    return r;
  };

  // For SSE-promoted responses in "stream" mode, synthesize a body that
  // serializes the typed events back to standards-compliant SSE wire bytes.
  // For "buffered", drain all events first.
  if (start.is_sse) {
    headers.set("Content-Type", "text/event-stream");
    headers.set("Cache-Control", "no-cache, no-transform");
    if (sseMode === "stream") {
      const body = new ReadableStream<Uint8Array>({
        start(controller) {
          (async () => {
            try {
              for await (const ev of stream.events) {
                controller.enqueue(serializeSseEvent(ev));
              }
              controller.close();
            } catch (e) {
              controller.error(e);
            }
          })();
        },
        cancel: () => stream.cancel(),
      });
      return finalize(new Response(body, { status: start.status_code, statusText, headers }));
    } else {
      // Buffered: collect everything before returning. Rare; mostly for tests.
      // CRITICAL: if the events iterator errors mid-stream, propagate via
      // `controller.error()` so the Response body surfaces the failure
      // instead of an unhandled rejection.
      return finalize(
        new Response(
          new ReadableStream<Uint8Array>({
            async start(controller) {
              try {
                const parts: Uint8Array[] = [];
                for await (const ev of stream.events) {
                  parts.push(serializeSseEvent(ev));
                }
                controller.enqueue(concat(parts));
                controller.close();
              } catch (e) {
                controller.error(e);
              }
            },
          }),
          { status: start.status_code, statusText, headers },
        ),
      );
    }
  }

  // Non-SSE: forward bodyStream directly. When the relay negotiated
  // compression pass-through (binary mode), upstream gzip/deflate bytes
  // arrive intact with a `Content-Encoding` header — pipe through
  // DecompressionStream so callers of `res.arrayBuffer()` / `.text()` see
  // plaintext. We then strip Content-Encoding (the body is now plain) and
  // Content-Length (the decompressed size differs).
  const encoding = headers.get("content-encoding")?.toLowerCase();
  let body: ReadableStream<Uint8Array> = stream.bodyStream;
  if (encoding === "gzip" || encoding === "deflate") {
    const Decomp = (globalThis as { DecompressionStream?: typeof DecompressionStream })
      .DecompressionStream;
    if (typeof Decomp === "function") {
      try {
        // DecompressionStream typing is BufferSource on the writable side;
        // pipeThrough wants matching Uint8Array. Cast through unknown — the
        // runtime contract is identical (Uint8Array IS a BufferSource).
        body = stream.bodyStream.pipeThrough(
          new Decomp(encoding) as unknown as ReadableWritablePair<Uint8Array, Uint8Array>,
        );
        headers.delete("content-encoding");
        headers.delete("content-length");
      } catch {
        // DecompressionStream rejected the format on this runtime — pass
        // the raw bytes through with the Content-Encoding header intact so
        // an external decoder can pick it up.
      }
    }
  }
  return finalize(
    new Response(body, {
      status: start.status_code,
      statusText,
      headers,
    }),
  );
}

const SSE_ENCODER = new TextEncoder();

/** Strip CR/LF from a field value so a hostile upstream can't inject synthetic
 * `event:` / `id:` / `data:` lines into our re-serialized SSE body. The
 * WHATWG SSE spec forbids these chars in field values; we replace with U+FFFD
 * rather than dropping to make corruption visible. */
function sanitizeSseField(value: string): string {
  return value.replace(/[\r\n]/g, "�");
}

function serializeSseEvent(ev: SseEvent): Uint8Array {
  const lines: string[] = [];
  if (ev.event && ev.event !== "message") {
    lines.push(`event: ${sanitizeSseField(ev.event)}`);
  }
  if (ev.id !== undefined) lines.push(`id: ${sanitizeSseField(ev.id)}`);
  if (ev.retry !== undefined) {
    // BUGFIX: the TS type is `number` but the
    // wire value comes from `JSON.parse` of an untrusted server frame — a
    // hostile server can send a string with embedded CRLF that bypasses
    // event/id sanitization. Coerce + clamp to a finite non-negative int
    // (which is what `retry:` accepts per WHATWG SSE spec anyway).
    const ms = Math.max(0, Math.floor(Number(ev.retry)));
    if (Number.isFinite(ms)) lines.push(`retry: ${ms}`);
  }
  // data.split("\n") correctly handles multi-line data by emitting one
  // `data:` line per source line — matches WHATWG SSE wire format and is the
  // inverse of the parser's `data_lines.join("\n")`. Also strip lone \r so
  // an upstream that sends \r without \n can't terminate a line prematurely.
  for (const dataLine of ev.data.split("\n")) {
    lines.push(`data: ${dataLine.replace(/\r/g, "�")}`);
  }
  lines.push("", "");
  return SSE_ENCODER.encode(lines.join("\n"));
}
